# Generated by Django 5.0.2 on 2024-03-23 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allpets',
            name='image',
            field=models.ImageField(upload_to='pimages/'),
        ),
    ]
