# Generated by Django 5.0.2 on 2024-03-23 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0002_alter_allpets_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='allpets',
            name='available',
        ),
        migrations.AlterField(
            model_name='allpets',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='pimages'),
        ),
    ]
